### PR TITLE
Adds cron triggers

### LINKED ISSUE #268: Set up cron jobs to trigger fetches
## Is your feature request related to a problem? Please describe.
Because the fetches can take a long time to complete (sometimes days), we need a method of triggering them other than HTTP.

## Describe the solution you'd like
Implement cron jobs to trigger fetches. These cron jobs should be locking, in other words multiple instances of the same fetch should not be able to run at the same time. See Aurora for examples of how to do this.

### PR DESCRIPTION
**Pull request by helrond**
fixes #268

### CODE REVIEW

**Comment by p-galligan** [comment]
I don't know if it matters since it passed the tests, but `Cartographer-deleted-arrangement_map_component` has no `.json` file extension.

**Comment by helrond** [comment]
Good catch, let me fix that!

**Comment by helrond** [comment]
Err, it looks like it's there to me, @p-galligan. Are you looking at an earlier diff?

**Comment by p-galligan** [comment]
That's weird. I'm not seeing it in the diff, but looking in my cloned repo, it looks like you may have added two files. One with and one without.

Screen Shot 2020-04-28 at 3 13 09 PM

Screen Shot 2020-04-28 at 3 11 27 PM

**Comment by helrond** [comment]
OIC yeah I shouldn't have committed that file. One sec.

**Pull request merged**
