### PR TITLE
Adds merger app, substantially restructures other apps.

### LINKED ISSUE #219: Move mergers to this app and restructure flow
## Is your feature request related to a problem? Please describe.
In order to avoid the possibility of incomplete data being indexed, and also to enhance the ability of validating data before is is merged, we need to rethink how the fetchers, transformers and mergers are structured. 

## Describe the solution you'd like
A number of fairly big chunks of work:
- Remove mergers from Scorpio and add them as an app in Pisces
- merge data before transforming
  - merging will need to fetch additional data from secondary data sources
- validate data after transformation
- persist data after validation

### PR DESCRIPTION
**Pull request by helrond**
This is a fairly large PR which adds a merger app, and moves some models around. Data is now fetched, merged, transformed and persisted all in Pisces.

There are still some TODOs noted in the code which have also been added as issues. Most of these are dependent on work outside of Pisces. 

fixes #219

### CODE REVIEW

**Comment by helrond** [comment]
@p-galligan this is a pretty invasive PR and also doesn't need to be approved immediately, so I'd suggest a slightly closer review of this, perhaps pulling this branch down and making sure the app spins up and everything looks good in the browser.

**Comment by p-galligan** [comment]
I managed to spin this up and the interface endpoints seem to be working ok for me.

Want me to try to run the tests locally as well?

**Comment by helrond** [comment]
@p-galligan I'm less concerned about tests passing and more that there's something not covered by tests. If you're not seeing anything that's fine; just don't want you to feel pressured to get an approval in ASAP.

**Comment by p-galligan** [comment]
Ok! I'll take some more time throughout the day to take a look and think about it.

**Pull request merged**
